In [5]:
import sys
from pathlib import Path
import pandas as pd


ROOT_DIR = Path(r"D:\BAPETEN\BAPETEN PROJEK\neta-eksplorasi")

if str(ROOT_DIR) not in sys.path:
    sys.path.insert(0, str(ROOT_DIR))


from services.google_services_own_account import (
    connect_google,
    read_excel,
)

FILE_ID_EXCEL = "1w5oauNrRO1WA9-t7nUWs6lHNLmbaaTUc"


def load_data_jadwal_function():
    drive, _ = connect_google()

    excel_data = read_excel(FILE_ID_EXCEL, drive)

    df = pd.read_excel(
        excel_data,
        sheet_name="Sheet1",
        engine="openpyxl",
    )

    return df

df = load_data_jadwal_function()

Berhasil

In [6]:
df.head()

,No,Jadwal ID,Kode Area,Tanggal Pelaksanaan,Jumlah Hari,Fas Id,Instansi,Alamat Id,Alamat (Inspeksi Lokasi Pemanfaatan),Propinsi,Sifat,Status Jadwal,Tanggal Inspeksi Terakhir,Nilai IKK
0,1,1877,Verifikasi Perizinan RS. Efarina Etaham Pemata...,2026-08-31 s/d 2026-09-04,5,13779.0,Hapoltakan Jaya Abadi,42067.0,"Jl. Pendeta J. Wismar Saragih, Bane, Kec. Sian...",Sumatera Utara,Verifikasi Perizinan,Radioterapi,2026-08-31 s/d 2026-09-04,2
1,2,1876,Verifikasi Perizinan PET-CT RS Awal Bros Pekan...,2026-08-31 s/d 2026-09-03,4,2675.0,Awal Bros Putra Medika,12738.0,"Jl. Jend. Sudirman No. 117, Tengkerang Selatan",Riau,Verifikasi Perizinan,Kedokteran Nuklir,2025-08-11 s/d 2025-08-15,2
2,3,1874,KALTIM KES 2026 Verifikasi RSUD dr. Kanujoso D...,2026-08-18 s/d 2026-08-21,4,1244.0,RSUD Dr. Kanujoso Djatiwibowo,45776.0,Jl. MT. Haryono No. 656 Ringroad,Kalimantan Timur,Verifikasi Perizinan,Kedokteran Nuklir,2025-10-06 s/d 2025-10-10,2
3,4,1873,Jawa Timur 1 FRZR,2026-09-21 s/d 2026-09-25,5,10802.0,Energi Sterila Higiena,43370.0,"Jl. Tambak Langon Indah I No. 19, Kelurahan Ta...",Jawa Timur,Berkala,Irradiator Tingkat IV,2023-12-18 s/d 2023-12-22,2
4,5,1872,Jawa Barat Kes Verifikasi - RS Mitra Keluarga ...,2026-08-18 s/d 2026-08-20,3,507.0,Proteindo Karyasehat,12841.0,"Jl. Pengasinan - Rawasemut, Margahayu",Jawa Barat,Verifikasi Perizinan,Radioterapi,2026-05-04 s/d 2026-05-08,2

In [7]:
df["Tahun"] = df["Tanggal Pelaksanaan"].astype(str).str[:4]

In [8]:
df.head()

,No,Jadwal ID,Kode Area,Tanggal Pelaksanaan,Jumlah Hari,Fas Id,Instansi,Alamat Id,Alamat (Inspeksi Lokasi Pemanfaatan),Propinsi,Sifat,Status Jadwal,Tanggal Inspeksi Terakhir,Nilai IKK,Tahun
0,1,1877,Verifikasi Perizinan RS. Efarina Etaham Pemata...,2026-08-31 s/d 2026-09-04,5,13779.0,Hapoltakan Jaya Abadi,42067.0,"Jl. Pendeta J. Wismar Saragih, Bane, Kec. Sian...",Sumatera Utara,Verifikasi Perizinan,Radioterapi,2026-08-31 s/d 2026-09-04,2,2026
1,2,1876,Verifikasi Perizinan PET-CT RS Awal Bros Pekan...,2026-08-31 s/d 2026-09-03,4,2675.0,Awal Bros Putra Medika,12738.0,"Jl. Jend. Sudirman No. 117, Tengkerang Selatan",Riau,Verifikasi Perizinan,Kedokteran Nuklir,2025-08-11 s/d 2025-08-15,2,2026
2,3,1874,KALTIM KES 2026 Verifikasi RSUD dr. Kanujoso D...,2026-08-18 s/d 2026-08-21,4,1244.0,RSUD Dr. Kanujoso Djatiwibowo,45776.0,Jl. MT. Haryono No. 656 Ringroad,Kalimantan Timur,Verifikasi Perizinan,Kedokteran Nuklir,2025-10-06 s/d 2025-10-10,2,2026
3,4,1873,Jawa Timur 1 FRZR,2026-09-21 s/d 2026-09-25,5,10802.0,Energi Sterila Higiena,43370.0,"Jl. Tambak Langon Indah I No. 19, Kelurahan Ta...",Jawa Timur,Berkala,Irradiator Tingkat IV,2023-12-18 s/d 2023-12-22,2,2026
4,5,1872,Jawa Barat Kes Verifikasi - RS Mitra Keluarga ...,2026-08-18 s/d 2026-08-20,3,507.0,Proteindo Karyasehat,12841.0,"Jl. Pengasinan - Rawasemut, Margahayu",Jawa Barat,Verifikasi Perizinan,Radioterapi,2026-05-04 s/d 2026-05-08,2,2026

In [9]:
print(df["Tahun"].dtype)

str