In [5]:
import sys
from pathlib import Path

ROOT_DIR = Path(r"D:\BAPETEN\BAPETEN PROJEK\neta-eksplorasi")

if str(ROOT_DIR) not in sys.path:
    sys.path.insert(0, str(ROOT_DIR))

from services.google_services_own_account import (
    connect_google,
    read_excel,
)

drive, sheets = connect_google()

In [6]:
import pandas as pd

ID_FILE_EXCEL = "1vqxcE_9L_T4VZ3z7g-BC8fp7StIMVSX_"

df_excel = read_excel(
    ID_FILE_EXCEL,
    drive
)

df = pd.read_excel(
        df_excel,
        sheet_name="clean_data",
        engine="openpyxl"
    )

df.head()

Berhasil

,No,Nama Instansi /Fasilitas,Alamat,Lokasi Pemanfaatan,Nomor LHI,Kelompok Kegiatan,Tanggal Inspeksi,Kategori Temuan,Status Bundling/ Temuan,Kode Temuan,Temuan dan Rekomendasi,Uraian Temuan,Uraian Rekomendasi,Tgl Batas Tindak Lanjut,Uraian Tindak Lanjut,Tgl Tindak Lanjut,Provinsi,Provinsi_Visualisasi,Kategori
0,1,Bhayangkara Tk.III Manado,Jl. Sam Ratulangi No. 326,"Jl. Sam Ratulangi No. 326,Manado,Sulawesi Utara",00053.01.12082.01.1.0426,Radiologi Diagnostik & Intervensional,2026-04-20 s/d 2026-04-24,1,terbuka,1.01.01,Tidak memiliki izin,Rumah Sakit Bhayangkara Tk. III Manado memilik...,-Rumah Sakit Bhayangkara Tk.III Manado dilaran...,2026-08-07 00:00:00,NaN,2026-05-05,Sulawesi Utara,Sulawesi Utara,Kategori I
1,2,BLU RSUP. Prof. Dr. R.D. Kandou Manado,Jl. Raya Tanawangko No 56 Manado Sulawesi Utara,Jl. Raya Tanawangko No 56 Manado Sulawesi Utar...,00073.01.00475.01.1.0426,Radiologi Diagnostik & Intervensional,2026-04-20 s/d 2026-04-24,1,terbuka,1.01.01,Tidak memiliki izin,- Terdapat 13 (tiga belas) Alat Radiologi Diag...,-BLU RSUP. Prof. Dr. R.D. Kandou Manado dilara...,2026-08-28 00:00:00,Surat Penonaktifan alat,2026-05-05,Sulawesi Utara,Sulawesi Utara,Kategori I
2,3,Conch North Sulawesi Cement,"The Suites Tower Lt. 19, Jl. Boulevard Pantai ...","The Suites Tower Lt. 19, Jl. Boulevard Pantai ...",00069.01.10409.08.1.0426,Gauging,2026-04-20 s/d 2026-04-24,1,tertutup,1.01.01,Tidak memiliki izin,"Terdapat 2 (dua) SRP yang belum memiliki izin,...",-PT. Conch North Sulawesi Cement dilarang meng...,0000-00-00,Untuk SRP Cf 252 dengan Kode Sumber 0191052 su...,2026-06-15,DKI Jakarta,DKI Jakarta,Kategori I
3,4,Vale Indonesia Tbk.,"The Energy Building, 31st Floor, SCBD Lot 11 A...","The Energy Building, 31st Floor, SCBD Lot 11 A...",00077.01.07945.20.1.0426,Fluoroskopi Bagasi,2026-04-20 s/d 2026-04-24,1,tertutup,1.01.01,Tidak memiliki izin,"Berdasarkan pemaparan pihak PT Vale Indonesia,...",-Pelaku usaha agar segera mengajukan permohona...,0000-00-00,Menindaklanjuti Surat Hasil Inspeksi Nomor : T...,2026-09-15,DKI Jakarta,DKI Jakarta,Kategori I
4,5,Vale Indonesia Tbk.,"The Energy Building, 31st Floor, SCBD Lot 11 A...","The Energy Building, 31st Floor, SCBD Lot 11 A...",00076.01.07945.08.1.0426,Gauging,2026-04-20 s/d 2026-04-24,1,terbuka,1.01.01,Tidak memiliki izin,"Berdasarkan pemaparan pihak PT Vale Indonesia,...",-Pelaku usaha agar segera mengajukan permohona...,2026-09-25 00:00:00,1. Mengajukan permohonan izin pemanfaatan selu...,2026-08-21,DKI Jakarta,DKI Jakarta,Kategori I

In [9]:
df.isnull().sum()

No                            0
Nama Instansi /Fasilitas      0
Alamat                        0
Lokasi Pemanfaatan            0
Nomor LHI                     0
Kelompok Kegiatan             0
Tanggal Inspeksi              0
Kategori Temuan               0
Status Bundling/ Temuan       0
Kode Temuan                   0
Temuan dan Rekomendasi        0
Uraian Temuan                 0
Uraian Rekomendasi            0
Tgl Batas Tindak Lanjut       0
Uraian Tindak Lanjut        267
Tgl Tindak Lanjut             0
Provinsi                      0
Provinsi_Visualisasi          0
Kategori                      0
dtype: int64

In [7]:
df_status = (
    df.groupby(["Kelompok Kegiatan", "Kode Temuan", "Status Bundling/ Temuan"])
      .size()
      .unstack(fill_value=0)
      .reset_index()
      .rename(columns={
          "Kelompok Kegiatan": "Jenis Kegiatan",
          "Kode Temuan": "Kode",
          "Terbuka": "terbuka",
          "Tertutup": "tertutup"
      })
)

df_status.insert(0, "No", range(1, len(df_status) + 1))

df_status["Total Temuan"] = df_status["terbuka"] + df_status["tertutup"]

df_status.style.hide(axis="index")

In [47]:
df_status = df_status.sort_values(
    by="Total Temuan",
    ascending=False
).reset_index(drop=True)

df_status.style.hide(axis="index")

In [ ]:
df.head()

,No,Nama Instansi /Fasilitas,Alamat,Lokasi Pemanfaatan,Nomor LHI,Kelompok Kegiatan,Tanggal Inspeksi,Kategori Temuan,Status Bundling/ Temuan,Kode Temuan,Temuan dan Rekomendasi,Uraian Temuan,Uraian Rekomendasi,Tgl Batas Tindak Lanjut,Uraian Tindak Lanjut,Tgl Tindak Lanjut,Provinsi,Provinsi_Visualisasi,Kategori
0,1,Bhayangkara Tk.III Manado,Jl. Sam Ratulangi No. 326,"Jl. Sam Ratulangi No. 326,Manado,Sulawesi Utara",00053.01.12082.01.1.0426,Radiologi Diagnostik & Intervensional,2026-04-20 s/d 2026-04-24,1,terbuka,1.01.01,Tidak memiliki izin,Rumah Sakit Bhayangkara Tk. III Manado memilik...,-Rumah Sakit Bhayangkara Tk.III Manado dilaran...,2026-08-07 00:00:00,NaN,2026-05-05,Sulawesi Utara,Sulawesi Utara,Kategori I
1,2,BLU RSUP. Prof. Dr. R.D. Kandou Manado,Jl. Raya Tanawangko No 56 Manado Sulawesi Utara,Jl. Raya Tanawangko No 56 Manado Sulawesi Utar...,00073.01.00475.01.1.0426,Radiologi Diagnostik & Intervensional,2026-04-20 s/d 2026-04-24,1,terbuka,1.01.01,Tidak memiliki izin,- Terdapat 13 (tiga belas) Alat Radiologi Diag...,-BLU RSUP. Prof. Dr. R.D. Kandou Manado dilara...,2026-08-28 00:00:00,Surat Penonaktifan alat,2026-05-05,Sulawesi Utara,Sulawesi Utara,Kategori I
2,3,Conch North Sulawesi Cement,"The Suites Tower Lt. 19, Jl. Boulevard Pantai ...","The Suites Tower Lt. 19, Jl. Boulevard Pantai ...",00069.01.10409.08.1.0426,Gauging,2026-04-20 s/d 2026-04-24,1,tertutup,1.01.01,Tidak memiliki izin,"Terdapat 2 (dua) SRP yang belum memiliki izin,...",-PT. Conch North Sulawesi Cement dilarang meng...,0000-00-00,Untuk SRP Cf 252 dengan Kode Sumber 0191052 su...,2026-06-15,DKI Jakarta,DKI Jakarta,Kategori I
3,4,Vale Indonesia Tbk.,"The Energy Building, 31st Floor, SCBD Lot 11 A...","The Energy Building, 31st Floor, SCBD Lot 11 A...",00077.01.07945.20.1.0426,Fluoroskopi Bagasi,2026-04-20 s/d 2026-04-24,1,tertutup,1.01.01,Tidak memiliki izin,"Berdasarkan pemaparan pihak PT Vale Indonesia,...",-Pelaku usaha agar segera mengajukan permohona...,0000-00-00,Menindaklanjuti Surat Hasil Inspeksi Nomor : T...,2026-09-15,DKI Jakarta,DKI Jakarta,Kategori I
4,5,Vale Indonesia Tbk.,"The Energy Building, 31st Floor, SCBD Lot 11 A...","The Energy Building, 31st Floor, SCBD Lot 11 A...",00076.01.07945.08.1.0426,Gauging,2026-04-20 s/d 2026-04-24,1,terbuka,1.01.01,Tidak memiliki izin,"Berdasarkan pemaparan pihak PT Vale Indonesia,...",-Pelaku usaha agar segera mengajukan permohona...,2026-09-25 00:00:00,1. Mengajukan permohonan izin pemanfaatan selu...,2026-08-21,DKI Jakarta,DKI Jakarta,Kategori I

In [8]:
mapping_ikk = {
    "01": "01 - Kode Perizinan",
    "02": "02 - Ketersediaan SDM",
    "03": "03 - Pemantauan Dosis Radiasi",
    "04": "04 - Pemantauan Kesehatan Pekerja Radiasi",
    "05": "05 - Ketersediaan Peralatan Keselamatan dan Keamanan SRP",
    "06": "06 - Pemantauan Paparan Radiasi Daerah Kerja",
    "07": "07 - Ketersediaan dan Kesesuaian Dokumen dan Rekaman Keselamatan dan Keamanan SRP"
}

df["kode"] = df["Kode Temuan"].astype(str).str[2:4]
df["Kode IKK"] = df["kode"].map(mapping_ikk).fillna(df["kode"])



df.head()

,No,Nama Instansi /Fasilitas,Alamat,Lokasi Pemanfaatan,Nomor LHI,Kelompok Kegiatan,Tanggal Inspeksi,Kategori Temuan,Status Bundling/ Temuan,Kode Temuan,...,Uraian Temuan,Uraian Rekomendasi,Tgl Batas Tindak Lanjut,Uraian Tindak Lanjut,Tgl Tindak Lanjut,Provinsi,Provinsi_Visualisasi,Kategori,kode,Kode IKK
0,1,Bhayangkara Tk.III Manado,Jl. Sam Ratulangi No. 326,"Jl. Sam Ratulangi No. 326,Manado,Sulawesi Utara",00053.01.12082.01.1.0426,Radiologi Diagnostik & Intervensional,2026-04-20 s/d 2026-04-24,1,terbuka,1.01.01,...,Rumah Sakit Bhayangkara Tk. III Manado memilik...,-Rumah Sakit Bhayangkara Tk.III Manado dilaran...,2026-08-07 00:00:00,NaN,2026-05-05,Sulawesi Utara,Sulawesi Utara,Kategori I,01,01 - Kode Perizinan
1,2,BLU RSUP. Prof. Dr. R.D. Kandou Manado,Jl. Raya Tanawangko No 56 Manado Sulawesi Utara,Jl. Raya Tanawangko No 56 Manado Sulawesi Utar...,00073.01.00475.01.1.0426,Radiologi Diagnostik & Intervensional,2026-04-20 s/d 2026-04-24,1,terbuka,1.01.01,...,- Terdapat 13 (tiga belas) Alat Radiologi Diag...,-BLU RSUP. Prof. Dr. R.D. Kandou Manado dilara...,2026-08-28 00:00:00,Surat Penonaktifan alat,2026-05-05,Sulawesi Utara,Sulawesi Utara,Kategori I,01,01 - Kode Perizinan
2,3,Conch North Sulawesi Cement,"The Suites Tower Lt. 19, Jl. Boulevard Pantai ...","The Suites Tower Lt. 19, Jl. Boulevard Pantai ...",00069.01.10409.08.1.0426,Gauging,2026-04-20 s/d 2026-04-24,1,tertutup,1.01.01,...,"Terdapat 2 (dua) SRP yang belum memiliki izin,...",-PT. Conch North Sulawesi Cement dilarang meng...,0000-00-00,Untuk SRP Cf 252 dengan Kode Sumber 0191052 su...,2026-06-15,DKI Jakarta,DKI Jakarta,Kategori I,01,01 - Kode Perizinan
3,4,Vale Indonesia Tbk.,"The Energy Building, 31st Floor, SCBD Lot 11 A...","The Energy Building, 31st Floor, SCBD Lot 11 A...",00077.01.07945.20.1.0426,Fluoroskopi Bagasi,2026-04-20 s/d 2026-04-24,1,tertutup,1.01.01,...,"Berdasarkan pemaparan pihak PT Vale Indonesia,...",-Pelaku usaha agar segera mengajukan permohona...,0000-00-00,Menindaklanjuti Surat Hasil Inspeksi Nomor : T...,2026-09-15,DKI Jakarta,DKI Jakarta,Kategori I,01,01 - Kode Perizinan
4,5,Vale Indonesia Tbk.,"The Energy Building, 31st Floor, SCBD Lot 11 A...","The Energy Building, 31st Floor, SCBD Lot 11 A...",00076.01.07945.08.1.0426,Gauging,2026-04-20 s/d 2026-04-24,1,terbuka,1.01.01,...,"Berdasarkan pemaparan pihak PT Vale Indonesia,...",-Pelaku usaha agar segera mengajukan permohona...,2026-09-25 00:00:00,1. Mengajukan permohonan izin pemanfaatan selu...,2026-08-21,DKI Jakarta,DKI Jakarta,Kategori I,01,01 - Kode Perizinan

In [8]:
df['Tgl Tindak Lanjut']

0     2026-05-05
1     2026-05-05
2     2026-06-15
3     2026-09-15
4     2026-08-21
         ...
739   2026-10-12
740   2026-10-12
741   2026-10-12
742   2026-10-12
743   2026-10-12
Name: Tgl Tindak Lanjut, Length: 744, dtype: datetime64[us]

In [17]:
import numpy as np
import pandas as pd

def tahun_temuan(file_olah, kategori, tahun="Semua", provinsi="Semua"):

    tanggal = pd.to_datetime(
        file_olah["Tgl Tindak Lanjut"],
        errors="coerce"
    )


    kondisi = file_olah['Kategori'] == kategori

    if isinstance(tahun, (list, tuple, np.ndarray)):
        if len(tahun) > 0:
            kondisi &= tanggal.dt.year.isin([int(t) for t in tahun])
    elif tahun != "Semua":
        kondisi &= tanggal.dt.year == int(tahun)


    if isinstance(provinsi, (list, tuple, np.ndarray)):
        if len(provinsi) > 0:
            kondisi &= file_olah["Provinsi"].isin(provinsi)
    elif provinsi != "Semua":
        kondisi &= file_olah["Provinsi"] == provinsi

    return len(file_olah.loc[kondisi])


tahun_temuan(df, "Kategori I", "2026", "Banten")

4

In [14]:
print(df.columns.tolist())

['No', 'Nama Instansi /Fasilitas', 'Alamat', 'Lokasi Pemanfaatan', 'Nomor LHI', 'Kelompok Kegiatan', 'Tanggal Inspeksi', 'Kategori Temuan', 'Status Bundling/ Temuan', 'Kode Temuan', 'Temuan dan Rekomendasi', 'Uraian Temuan', 'Uraian Rekomendasi', 'Tgl Batas Tindak Lanjut', 'Uraian Tindak Lanjut', 'Tgl Tindak Lanjut', 'Provinsi', 'Provinsi_Visualisasi', 'Kategori']